//
// Created by Luke on 07/08/2025.
//

#ifndef MINECRAFT_WORLDCONSTANTS_H
#define MINECRAFT_WORLDCONSTANTS_H

#define WORLD_SIZE_X 4
#define WORLD_SIZE_Y 4
#define WORLD_SIZE_Z 4

#define CHUNK_SIZE_X 4
#define CHUNK_SIZE_Y 4
#define CHUNK_SIZE_Z 4

#define CUBE_FACES 6

#define WORLD_MAX_VERTICES ((WORLD_SIZE_X * WORLD_SIZE_Y * WORLD_SIZE_Z) * \
(CHUNK_SIZE_X * CHUNK_SIZE_Y * CHUNK_SIZE_Z) * \
CUBE_FACES * 30)

#define OVERWORLD 0

#endif //MINECRAFT_WORLDCONSTANTS_H