//
// Created by Luke on 07/08/2025.
//

#ifndef MINECRAFT_WORLDCONSTANTS_H
#define MINECRAFT_WORLDCONSTANTS_H

#include <glad/glad.h>

#define WORLD_SIZE_X 16
#define WORLD_SIZE_Y 16
#define WORLD_SIZE_Z 1

#define CHUNK_SIZE_X 64
#define CHUNK_SIZE_Y 64
#define CHUNK_SIZE_Z 64

#define WORLD_SPAWN_COORDS glm::vec3(0, 30, 0)

#define CUBE_FACES 6

#define WORLD_MAX_VERTICES ((WORLD_SIZE_X * WORLD_SIZE_Y * WORLD_SIZE_Z) * \
(CHUNK_SIZE_X * CHUNK_SIZE_Y * CHUNK_SIZE_Z) * \
CUBE_FACES * 30)

#define OVERWORLD 0

#endif //MINECRAFT_WORLDCONSTANTS_H